/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Aviator0 (https://sketchfab.com/Aviator0)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/airbus-a320-with-realistic-cockpit-80bb2dd52a474106b3d3d2fa5aa8c2b1
title: Airbus A320 (With Realistic cockpit)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from "@react-three/fiber";

export default function Car({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model.glb')

  useFrame(({ clock }) => {
    group.current.rotation.x = Math.sin(clock.getElapsedTime())
  })
  return (
    <group ref={group} {...props} dispose={null} position={[10,1,-20]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart1_Meshpart1Mtl_0.geometry} material={materials.Meshpart1Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart2_Meshpart1Mtl_0.geometry} material={materials.Meshpart1Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart3_Meshpart3Mtl_0.geometry} material={materials.Meshpart3Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart4_Meshpart4Mtl_0.geometry} material={materials.Meshpart4Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart5_Meshpart5Mtl_0.geometry} material={materials.Meshpart5Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart6_Meshpart3Mtl_0.geometry} material={materials.Meshpart3Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart7_Meshpart4Mtl_0.geometry} material={materials.Meshpart4Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart8_Meshpart8Mtl_0.geometry} material={materials.Meshpart8Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart9_Meshpart9Mtl_0.geometry} material={materials.Meshpart9Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart10_Meshpart9Mtl_0.geometry} material={materials.Meshpart9Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart11_Meshpart9Mtl_0.geometry} material={materials.Meshpart9Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart12_Meshpart3Mtl_0.geometry} material={materials.Meshpart3Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart13_Meshpart13Mtl_0.geometry} material={materials.Meshpart13Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart14_Meshpart14Mtl_0.geometry} material={materials.Meshpart14Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart15_Meshpart15Mtl_0.geometry} material={materials.Meshpart15Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart16_Meshpart16Mtl_0.geometry} material={materials.Meshpart16Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart17_Meshpart17Mtl_0.geometry} material={materials.Meshpart17Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart18_Meshpart18Mtl_0.geometry} material={materials.Meshpart18Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart19_Meshpart19Mtl_0.geometry} material={materials.Meshpart19Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart20_Meshpart20Mtl_0.geometry} material={materials.Meshpart20Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart21_Meshpart19Mtl_0.geometry} material={materials.Meshpart19Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart22_Meshpart22Mtl_0.geometry} material={materials.Meshpart22Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart23_Meshpart23Mtl_0.geometry} material={materials.Meshpart23Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart24_Meshpart24Mtl_0.geometry} material={materials.Meshpart24Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart25_Meshpart25Mtl_0.geometry} material={materials.Meshpart25Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart26_Meshpart25Mtl_0.geometry} material={materials.Meshpart25Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart27_Meshpart9Mtl_0.geometry} material={materials.Meshpart9Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart28_Meshpart4Mtl_0.geometry} material={materials.Meshpart4Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart29_Meshpart29Mtl_0.geometry} material={materials.Meshpart29Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart30_Meshpart4Mtl_0.geometry} material={materials.Meshpart4Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart31_Meshpart31Mtl_0.geometry} material={materials.Meshpart31Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart32_Meshpart1Mtl_0.geometry} material={materials.Meshpart1Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart33_Meshpart33Mtl_0.geometry} material={materials.Meshpart33Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart34_Meshpart14Mtl_0.geometry} material={materials.Meshpart14Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart35_Meshpart20Mtl_0.geometry} material={materials.Meshpart20Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart36_Meshpart36Mtl_0.geometry} material={materials.Meshpart36Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart37_Meshpart37Mtl_0.geometry} material={materials.Meshpart37Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart38_Meshpart3Mtl_0.geometry} material={materials.Meshpart3Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart39_Meshpart39Mtl_0.geometry} material={materials.Meshpart39Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart40_Meshpart40Mtl_0.geometry} material={materials.Meshpart40Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart41_Meshpart41Mtl_0.geometry} material={materials.Meshpart41Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart42_Meshpart42Mtl_0.geometry} material={materials.Meshpart42Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart43_Meshpart43Mtl_0.geometry} material={materials.Meshpart43Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart44_Meshpart5Mtl_0.geometry} material={materials.Meshpart5Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart45_Meshpart45Mtl_0.geometry} material={materials.Meshpart45Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart46_Meshpart36Mtl_0.geometry} material={materials.Meshpart36Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart47_Meshpart36Mtl_0.geometry} material={materials.Meshpart36Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart48_Meshpart3Mtl_0.geometry} material={materials.Meshpart3Mtl} />
          </group>
          <group scale={13.87}>
            <mesh geometry={nodes.Meshpart49_Meshpart3Mtl_0.geometry} material={materials.Meshpart3Mtl} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
