/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 2ad700ss (https://sketchfab.com/2ad700ss)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/squad-game-doll-beauty-4792f692c8ea488e9d04f35de8612e48
title: SQUAD GAME DOLL BEAUTY
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'
import {gsap} from "gsap";
import {useObservableContext} from "./state/useObservable";

export default function Girl({ ...props }) {
  const group=useObservableContext()
  const { nodes, materials } = useGLTF('/girl.glb')
    const start=()=>{
        const doll=group.current
        if(doll){
            gsap.to(doll.rotation,{duration:2, y:3})
            gsap.to(doll.rotation,{duration:1.5, y:0})
        }
    }

    setInterval(()=>{
      start()
    },3000)

  return (
    <group position={[0,0,2]} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.doll} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.doll} />
      </group>
    </group>
  )
}

useGLTF.preload('/girl.glb')
